BASE = ../rai

OPTIM = fast_debug

#OBJS = main.o completionBandits.o solver_uct.o

DEPEND = KOMO Core Geo Kin Gui Optim PathAlgos Logic Search LGP

LIBS += -lpthread

include $(BASE)/makeutils/generic.mk
